### ISSUE TITLE
os.Exit() call drops last log message

### ISSUE THREAD

**Issue by mhmxs** [linode/cluster-api-provider-linode#76]
It is hard to identify errors in `main`, because the system doesn't have enough time to flush logs.

https://github.com/linode/cluster-api-provider-linode/blob/1bfa6dc02aebd64984cae98d48e8ebee943f0c99/cmd/main.go#L61

**Comment by cbzzz** [comment]
I think the issue was with that one specific error message gets called before the `setupLogger` is setup [here](https://github.com/linode/cluster-api-provider-linode/blob/1bfa6dc02aebd64984cae98d48e8ebee943f0c99/cmd/main.go#L82). Please let me know if https://github.com/linode/cluster-api-provider-linode/pull/82 fixes your issue.
